### ISSUE TITLE
When downloading a user profile, the reposts are not downloaded.

### ISSUE THREAD

**Issue by moxtec** [Bukk94/CoubDownloader#1]
When downloading a user profile, the reposts are not downloaded

CoubDownloader crawls the repost links. But the repost link is a redirection to the original post

Example:
https://coub.com/view/2hjyi7 -> https://coub.com/view/2h2esr

![image](https://user-images.githubusercontent.com/73540223/159143055-d7ffdaea-b71a-44ea-80cc-f654684166c5.png)

It seems CoubDownloader have a Problem with that

Besides, Own Coubs and Repost are not separated

Big Thanks for a so easy to use Tool

**Comment by Bukk94** [comment]
This is good point actually! It indeed returns 302 with a redirect to the original post. I'll try to implement this within a day and release a new version.

**Comment by moxtec** [comment]
Problem completely Solved in Release 0.5
