### ISSUE TITLE
hi,how to clear watermark?

### ISSUE THREAD

**Issue by geniuskai** [Bukk94/CoubDownloader#5]
how to clear watermark?谢谢大佬

**Comment by Bukk94** [comment]
Hi, unfortunately, there is no reliable way to remove the watermark. We found couple hidden API endpoints and fields that contains coubs without watermark, but they were really low quality (for example original video was 1920x1080 but without watermark video was 400x300).
Unless something changed, this tool cannot provide videos without watermark, sorry :/
