### ISSUE TITLE
Error 404 on download attempt

### ISSUE THREAD

**Issue by aeroFBW** [Bukk94/CoubDownloader#7]
I have tried your program and I can't seem to get it to download bookmarks and/or likes. I have tried downloading channels and that works so it can crawl the site but if i ask it to download bookmarks and once i give it the access token it 404s

**Comment by Bukk94** [comment]
Hi,
it seems that they removed `v2/users/me` endpoint that I was using. Thankfully, this is easy to fix. I'll soon release v0.11.

**Comment by Bukk94** [comment]
Try this release @aeroFBW 
https://github.com/Bukk94/CoubDownloader/releases/tag/v0.11

**Comment by aeroFBW** [comment]
Hi,
I have downloaded the new version and it seems that for this version in particular the GUI does not want to pop up when i run it. I have tried both the basic and full releases

**Comment by aeroFBW** [comment]
it seems to be working i just had to download .net 8.0, Thank you for your help and for making this program
